# Loding Dataset

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("Dataset/amazon_enriched.csv")
data.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,...,return_rate_pct,demand_tier,is_seasonal_product,total_orders,total_units_sold,gross_revenue_inr,net_revenue_inr,total_profit_inr,first_sale_date,last_sale_date
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...",...,3.83,High,False,464,616,224761.78,210876.15,-12231.10,2023-01-06,2025-12-28
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...",...,6.24,High,False,346,479,88461.57,82552.87,9507.70,2023-01-01,2025-12-30
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...",...,3.99,Medium,False,174,225,60616.08,54976.05,24489.41,2023-01-18,2025-12-25
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...",...,7.45,High,False,487,633,193026.72,171559.00,10026.27,2023-01-01,2025-12-30
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...",...,7.45,High,False,359,479,66653.00,58800.62,4640.54,2023-01-04,2025-12-30

# Clean Dataset

In [4]:
data.shape

(1465, 39)

In [5]:
data.describe()

,mrp_inr,selling_price_inr,cost_price_inr,profit_margin_pct,stock_quantity,avg_delivery_days,return_rate_pct,total_orders,total_units_sold,gross_revenue_inr,net_revenue_inr,total_profit_inr
count,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1.465000e+03,1.465000e+03,1465.00000
mean,5446.219304,3125.439884,2538.617556,21.453195,435.941980,3.810922,4.973631,190.480546,252.509898,4.201019e+05,3.879582e+05,47681.49243
std,10874.374998,6944.274066,5935.119313,8.988895,262.710376,2.083081,1.428127,130.614243,173.385606,7.669658e+05,7.075901e+05,88188.27689
min,39.000000,39.000000,31.060000,6.000000,0.000000,1.000000,0.500000,12.000000,16.000000,3.515140e+03,3.128140e+03,-231326.62000
25%,800.000000,325.000000,260.500000,14.830000,210.000000,2.000000,4.020000,101.000000,135.000000,7.263678e+04,6.729155e+04,4285.68000
50%,1690.000000,799.000000,615.700000,19.370000,435.000000,4.000000,4.950000,158.000000,208.000000,1.758189e+05,1.625195e+05,15797.85000
75%,4295.000000,1999.000000,1586.420000,28.690000,660.000000,5.000000,5.880000,247.000000,325.000000,3.839057e+05,3.551768e+05,49889.07000
max,139900.000000,77990.000000,73218.570000,47.300000,899.000000,9.000000,10.660000,1072.000000,1418.000000,8.797807e+06,8.568651e+06,812315.86000

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
 16  brand                1465 non-null   str
 17  seller_id            1465 non-null   str
 18  seller_name          1465 non-null   str
 19  main_category        1465 non-null   str
 20  launch_date          1465 non-null   str
 21  mrp_inr              1465 non-null   float64
 22  selling_price_inr    1465 non-null   float64
 23  cost_price_inr       1465 non-null   float64
 24  profit_margin_pct    1465 non-null   float64
 25  stock_quantity       1465 non-null   int64
 26  warehouse_region     1465 non-null   str
 27  fulfilment_type      1465 non-null   str
 28  avg_delivery_days    1465 non-null   int64
 29  return_rate_pct      1465 non-null   float64
 30  demand_tier          1465 non-null   str
 31  is_seasonal_product  1465 non-null   bool
 32  total_orders         1465 non-null   int64
 33  total_units_sold     1465 non-null   int64
 34  gross_revenue_inr    1465 non-null   float64
 35  net_revenue_inr      1465 non-null   float64
 36  total_profit_inr     1465 non-null   float64
 37  first_sale_date      1465 non-null   str
 38  last_sale_date       1465 non-null   str
dtypes: bool(1), float64(8), int64(4), str(26)
memory usage: 436.5 KB

In [7]:
# Drop unnecessary columns

text_cols = ["about_product", "review_content", "user_id", "img_link", "product_link"]

# keep product_id in both so you can rejoin later
text_df = data[["product_id"] + text_cols].copy()

data = data.drop(columns=text_cols)

In [8]:
data["discounted_price"] = data["discounted_price"].str.replace(r"[₹,]", "", regex=True).astype(float)

data["actual_price"] = data["actual_price"].str.replace(r"[₹,]", "", regex=True).astype(float)

data["discount_percentage"] = data["discount_percentage"].str.rstrip("%").astype(float) / 100

data["rating"] = pd.to_numeric(data["rating"], errors="coerce") 

data["rating_count"] = data["rating_count"].str.replace(",", "", regex=False).astype("Int64")

date_cols = ["launch_date", "first_sale_date", "last_sale_date"]
for c in date_cols:
    data[c] = pd.to_datetime(data[c], format="%Y-%m-%d", errors="coerce")

In [9]:
# Adding New column for future use

data["sale_span_days"]    = (data["last_sale_date"] - data["first_sale_date"]).dt.days
data["age_at_first_sale"] = (data["first_sale_date"] - data["launch_date"]).dt.days

In [10]:
# Spliting category

data[["cat_l1", "cat_l2", "cat_l3"]] = data["category"].str.split("|", expand=True).iloc[:, :3]

In [11]:
# Drop Null Value

data = data.dropna(subset=["rating", "rating_count", "cat_l3"])

print(data.isnull().sum()[lambda s: s > 0])

Series([], dtype: int64)

In [12]:
data.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_name,review_id,...,gross_revenue_inr,net_revenue_inr,total_profit_inr,first_sale_date,last_sale_date,sale_span_days,age_at_first_sale,cat_l1,cat_l2,cat_l3
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,0.64,4.2,24269,"Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...",...,224761.78,210876.15,-12231.10,2023-01-06,2025-12-28,1087,1302,Computers&Accessories,Accessories&Peripherals,Cables&Accessories
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,0.43,4.0,43994,"ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...",...,88461.57,82552.87,9507.70,2023-01-01,2025-12-30,1094,1590,Computers&Accessories,Accessories&Peripherals,Cables&Accessories
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,0.90,3.9,7928,"Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...",...,60616.08,54976.05,24489.41,2023-01-18,2025-12-25,1072,1753,Computers&Accessories,Accessories&Peripherals,Cables&Accessories
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,0.53,4.2,94363,"Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...",...,193026.72,171559.00,10026.27,2023-01-01,2025-12-30,1094,1145,Computers&Accessories,Accessories&Peripherals,Cables&Accessories
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,0.61,4.2,16905,"rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...",...,66653.00,58800.62,4640.54,2023-01-04,2025-12-30,1091,732,Computers&Accessories,Accessories&Peripherals,Cables&Accessories

# Feature engineering

In [13]:
data.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'user_name', 'review_id', 'review_title', 'brand', 'seller_id',
       'seller_name', 'main_category', 'launch_date', 'mrp_inr',
       'selling_price_inr', 'cost_price_inr', 'profit_margin_pct',
       'stock_quantity', 'warehouse_region', 'fulfilment_type',
       'avg_delivery_days', 'return_rate_pct', 'demand_tier',
       'is_seasonal_product', 'total_orders', 'total_units_sold',
       'gross_revenue_inr', 'net_revenue_inr', 'total_profit_inr',
       'first_sale_date', 'last_sale_date', 'sale_span_days',
       'age_at_first_sale', 'cat_l1', 'cat_l2', 'cat_l3'],
      dtype='str')

In [14]:
data['revenue_per_order'] = data.gross_revenue_inr / data.total_orders
data['units_per_order'] = data.total_units_sold / data.total_orders
data['sell_through'] = data.total_units_sold / (data.total_units_sold + data.stock_quantity)
data['active_days']=(data.last_sale_date - data.first_sale_date).dt.days.clip(lower=1)
data['units_per_day']=data.total_units_sold / data.active_days
data['product_age_days']=(pd.Timestamp('2026-09-20') - data.launch_date).dt.days
data['discount_depth']=(data.mrp_inr - data.selling_price_inr) / data.mrp_inr

data.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_name,review_id,...,cat_l1,cat_l2,cat_l3,revenue_per_order,units_per_order,sell_through,active_days,units_per_day,product_age_days,discount_depth
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,0.64,4.2,24269,"Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...",...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,484.400388,1.327586,0.518519,1087,0.566697,2655,0.636943
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,0.43,4.0,43994,"ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...",...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,255.669277,1.384393,0.460577,1094,0.437843,2948,0.429799
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,0.90,3.9,7928,"Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...",...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,348.368276,1.293103,0.266272,1072,0.209888,3094,0.895208
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,0.53,4.2,94363,"Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...",...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,396.358768,1.299795,0.489938,1094,0.578611,2503,0.529328
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,0.61,4.2,16905,"rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...",...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,185.662953,1.334262,0.360693,1091,0.439047,2087,0.614035

In [15]:
data.describe().round(3)

,discounted_price,actual_price,discount_percentage,rating,rating_count,launch_date,mrp_inr,selling_price_inr,cost_price_inr,profit_margin_pct,...,last_sale_date,sale_span_days,age_at_first_sale,revenue_per_order,units_per_order,sell_through,active_days,units_per_day,product_age_days,discount_depth
count,1454.000,1454.000,1454.000,1454.000,1454.0,1454,1454.000,1454.000,1454.000,1454.000,...,1454,1454.000,1454.000,1454.000,1454.000,1454.000,1454.000,1454.000,1454.000,1454.000
mean,3115.186,5430.478,0.477,4.095,18358.151,2020-05-11 03:04:12.544704,5431.716,3115.316,2529.815,21.479,...,2025-12-25 04:14:31.526822,1079.254,974.795,3950.122,1.324,0.404,1079.254,0.233,2322.872,0.477
min,39.000,39.000,0.000,2.000,2.0,2018-01-28 00:00:00,39.000,39.000,31.060,6.000,...,2025-09-01 00:00:00,802.000,122.000,49.483,1.000,0.024,802.000,0.017,1478.000,0.000
25%,325.000,800.000,0.320,4.000,1191.5,2019-02-28 06:00:00,800.000,325.000,261.270,14.830,...,2025-12-25 00:00:00,1077.000,548.250,392.082,1.286,0.226,1077.000,0.125,1889.250,0.321
50%,799.000,1670.000,0.500,4.100,5187.0,2020-06-16 12:00:00,1692.500,799.000,615.130,19.400,...,2025-12-28 00:00:00,1086.000,942.500,992.193,1.326,0.348,1086.000,0.193,2286.500,0.500
75%,1999.000,4295.000,0.630,4.300,17342.25,2021-07-18 18:00:00,4295.000,1999.000,1585.475,28.712,...,2025-12-30 00:00:00,1091.000,1416.000,2574.532,1.363,0.547,1091.000,0.298,2760.750,0.629
max,77990.000,139900.000,0.940,5.000,426973.0,2022-09-03 00:00:00,139900.000,77990.000,73218.570,47.300,...,2025-12-31 00:00:00,1095.000,1916.000,90699.045,1.600,1.000,1095.000,1.297,3157.000,0.941
std,6936.911,10869.620,0.216,0.290,42871.119,NaN,10869.166,6936.881,5928.603,9.000,...,NaN,22.754,485.861,8862.017,0.064,0.231,22.754,0.158,485.570,0.216

# EDA